# For development only

name: CodeTech
services:
  redis:
    image: redis:latest
    container_name: code-tech-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    container_name: code-tech-loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    container_name: code-tech-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"

    depends_on:
      - loki
      - prom-server

volumes:
  redis-data:

# echo "hba_file = '/var/lib/postgresql/conf/pg_hba.conf'" >> /var/lib/postgresql/data/postgresql.conf